FROM python:3.13-slim

WORKDIR /app

COPY requirements.dev.txt /app/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /app/requirements.txt

COPY . /app

EXPOSE 4321
CMD ["fastapi", "run", "analysis_api/main.py", "--port", "4321"]
